---
- name: Install Brave browser and other essential packages
  hosts: all
  become: yes
  tasks:
    # Brave Browser Installation
    - name: Check if Brave browser is installed
      ansible.builtin.command: which brave-browser
      register: brave_check
      failed_when: false
      changed_when: false

    - name: Install Brave browser prerequisites
      block:
        - name: Install curl
          ansible.builtin.apt:
            name: curl
            state: present

        - name: Add Brave browser repository key
          ansible.builtin.apt_key:
            url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
            state: present

        - name: Add Brave browser repository
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
            state: present
            filename: brave-browser

        - name: Install Brave browser
          ansible.builtin.apt:
            name: brave-browser
            state: present
            update_cache: yes
      when: brave_check.rc != 0

    - name: Display Brave status
      ansible.builtin.debug:
        msg: "{{ 'Brave browser installed' if brave_check.rc == 0 else 'Brave browser was just installed' }}"

    # Install other essential packages
    - name: Install essential packages
      ansible.builtin.apt:
        name:
          - pass
          - git
          - htop
          - terminator
          - vim
          - gawk
          - jq
          - vlc
          - xclip
          - rustc
          - ufw
        state: present
        update_cache: yes

    # Configure UFW
    - name: Configure UFW firewall
      block:
        - name: Enable UFW
          ansible.builtin.ufw:
            state: enabled
            policy: deny

        - name: Allow SSH
          ansible.builtin.ufw:
            rule: allow
            name: OpenSSH
      when: ansible_facts.os_family == "Debian"

    - name: Display completion message
      ansible.builtin.debug:
        msg: "All packages installed and configured on {{ inventory_hostname }}"
