---
- name: Install VirtualBox on Debian-based systems (e.g., Linux Mint, LMDE)
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Determine distro codename for VirtualBox repo
      shell: |
        if grep -q '^ID_LIKE=.*ubuntu' /etc/os-release 2>/dev/null; then
          codename=$(grep '^UBUNTU_CODENAME=' /etc/os-release | cut -d= -f2 | tr -d '"')
        else
          # Debian or LMDE
          debian_ver=$(cat /etc/debian_version 2>/dev/null | cut -d. -f1)
          case "${debian_ver:-12}" in
            12) codename="bookworm" ;;
            11) codename="bullseye" ;;
            *) codename="bookworm" ;;
          esac
        fi
        echo $codename
      register: distro_codename
      changed_when: false

    - name: Download and dearmor VirtualBox GPG key
      shell: wget -qO- https://www.virtualbox.org/download/oracle_vbox_2016.asc | gpg --dearmor -o /usr/share/keyrings/oracle-virtualbox-2016.gpg
      args:
        creates: /usr/share/keyrings/oracle-virtualbox-2016.gpg

    - name: Add VirtualBox APT repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian {{ distro_codename.stdout }} contrib"
        state: present
        filename: oracle-virtualbox
        update_cache: yes

    - name: Install VirtualBox
      apt:
        name: virtualbox-7.1
        state: present
        update_cache: yes
