---
- name: Gather and Report Host System Information
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Collect ALL facts
      setup:
        gather_subset: all

    - name: Extract CPU MHz from /proc/cpuinfo
      shell: grep "MHz" /proc/cpuinfo | awk '{print $4}' | cut -d. -f1
      register: cpu_mhz_raw
      changed_when: false

    - name: Build list of CPU speeds
      set_fact:
        cpu_speeds: "{{ cpu_mhz_raw.stdout_lines | map('int') | list }}"

    - name: Calculate average CPU speed
      set_fact:
        avg_cpu_speed: >-
          {% if cpu_speeds | length > 0 %}
            {{ (cpu_speeds | sum / cpu_speeds | length) | round(0) | int }}
          {% else %}
            N/A
          {% endif %}

    - name: Format uptime
      set_fact:
        uptime_formatted: >-
          {% set s = ansible_uptime_seconds | int %}
          {% set d = s // 86400 %}
          {% set h = (s % 86400) // 3600 %}
          {% set m = (s % 3600) // 60 %}
          {% set sec = s % 60 %}
          {{ '%4dd %2dh %2dm %2ds' | format(d, h, m, sec) }}

    - name: Get process count
      shell: ps -A --no-headers | wc -l
      register: proc_count
      changed_when: false

    - name: Display Host Report (REAL NEWLINES, NO ESCAPES)
      ansible.builtin.shell: |
        printf '%s\n' \
          '========================================' \
          'HOST: {{ inventory_hostname }}' \
          '========================================' \
          'System:' \
          '  Kernel: {{ ansible_kernel }} arch: {{ ansible_architecture }} bits: {{ ansible_userspace_bits }}' \
          '  Distro: {{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }}' \
          '' \
          'Machine:' \
          '  Model: {{ ansible_product_name | default("N/A") }}' \
          '  Serial: {{ ansible_product_serial | default("<hidden>") }}' \
          '  BIOS: {{ ansible_bios_version | default("N/A") }} ({{ ansible_bios_date | default("N/A") }})' \
          '' \
          'CPU:' \
          '  Model: {{ ansible_processor[2] | default("Unknown") }}' \
          '  Cores: {{ ansible_processor_vcpus }} (SMT: {{ "enabled" if ansible_processor_threads_per_core > 1 else "disabled" }})' \
          '  Speed: {{ avg_cpu_speed }} MHz (avg)' \
          '' \
          'Memory:' \
          '  Total: {{ (ansible_memtotal_mb / 1024) | round(2) }} GiB' \
          '  Used: {{ (ansible_memory_mb.real.used / 1024) | round(2) }} GiB ({{ ((ansible_memory_mb.real.used / ansible_memtotal_mb) * 100) | round(1) }}%)' \
          '' \
          'Network:' \
          {% for iface in ansible_interfaces | reject('equalto', 'lo') %}
          {% set data = ansible_facts[iface] | default({}) %}
          {% if data.device is defined %}
          '  IF: {{ iface }} state: {{ "up" if data.active | default(false) else "down" }} mac: {{ data.macaddress | default("<filtered>") }}' \
          {% if data.ipv4 is defined %}
          '    IP: {{ data.ipv4.address }}' \
          {% endif %}
          {% endif %}
          {% endfor %} \
          '' \
          'Drives:' \
          {% for mount in ansible_mounts %}
          '  {{ mount.device }} ({{ mount.fstype }}) size: {{ (mount.size_total / 1024 / 1024 / 1024) | round(2) }} GiB' \
          '    Mount: {{ mount.mount }} used: {{ ((mount.size_total - mount.size_available) / 1024 / 1024 / 1024) | round(2) }} GiB ({{ (((mount.size_total - mount.size_available) / mount.size_total) * 100) | round(1) }}%)' \
          {% endfor %} \
          '' \
          'Swap:' \
          '  Total: {{ (ansible_swaptotal_mb / 1024) | round(2) }} GiB' \
          '  Used: {{ ((ansible_swaptotal_mb - ansible_swapfree_mb) / 1024) | round(2) }} GiB' \
          '' \
          'Uptime: {{ uptime_formatted }}' \
          'Processes: {{ proc_count.stdout | int }}' \
          '' \
          'Control Host: {{ "Yes" if hostvars[inventory_hostname].is_control_host | default(false) else "No" }}'
      args:
        executable: /bin/bash
      changed_when: false

    - name: Ensure reports directory exists
      file:
        path: reports
        state: directory
      delegate_to: localhost
      run_once: true

    - name: Save report to file
      copy:
        content: |
          ========================================
          HOST: {{ inventory_hostname }}
          ========================================
          System:
            Kernel: {{ ansible_kernel }} arch: {{ ansible_architecture }} bits: {{ ansible_userspace_bits }}
            Distro: {{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }}

          Machine:
            Model: {{ ansible_product_name | default('N/A') }}
            Serial: {{ ansible_product_serial | default('<hidden>') }}
            BIOS: {{ ansible_bios_version | default('N/A') }} ({{ ansible_bios_date | default('N/A') }})

          CPU:
            Model: {{ ansible_processor[2] | default('Unknown') }}
            Cores: {{ ansible_processor_vcpus }} (SMT: {{ 'enabled' if ansible_processor_threads_per_core > 1 else 'disabled' }})
            Speed: {{ avg_cpu_speed }} MHz (avg)

          Memory:
            Total: {{ (ansible_memtotal_mb / 1024) | round(2) }} GiB
            Used: {{ (ansible_memory_mb.real.used / 1024) | round(2) }} GiB ({{ ((ansible_memory_mb.real.used / ansible_memtotal_mb) * 100) | round(1) }}%)

          Network:
            {% for iface in ansible_interfaces | reject('equalto', 'lo') %}
            {% set data = ansible_facts[iface] | default({}) %}
            {% if data.device is defined %}
            IF: {{ iface }} state: {{ 'up' if data.active | default(false) else 'down' }} mac: {{ data.macaddress | default('<filtered>') }}
            {% if data.ipv4 is defined %}  IP: {{ data.ipv4.address }}{% endif %}
            {% endif %}
            {% endfor %}

          Drives:
            {% for mount in ansible_mounts %}
            {{ mount.device }} ({{ mount.fstype }}) size: {{ (mount.size_total / 1024 / 1024 / 1024) | round(2) }} GiB
              Mount: {{ mount.mount }} used: {{ ((mount.size_total - mount.size_available) / 1024 / 1024 / 1024) | round(2) }} GiB ({{ (((mount.size_total - mount.size_available) / mount.size_total) * 100) | round(1) }}%)
            {% endfor %}

          Swap:
            Total: {{ (ansible_swaptotal_mb / 1024) | round(2) }} GiB
            Used: {{ ((ansible_swaptotal_mb - ansible_swapfree_mb) / 1024) | round(2) }} GiB

          Uptime: {{ uptime_formatted }}
          Processes: {{ proc_count.stdout | int }}

          Control Host: {{ 'Yes' if hostvars[inventory_hostname].is_control_host | default(false) else 'No' }}
        dest: "reports/{{ inventory_hostname }}_report.txt"
      delegate_to: localhost
