---
- name: Get detailed CPU information from /proc/cpuinfo
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Read and parse /proc/cpuinfo
      shell: |
        # Get processor model
        MODEL=$(grep -m1 "model name" /proc/cpuinfo | cut -d: -f2 | sed 's/^[ \t]*//')
        
        # Get vendor/manufacturer
        VENDOR=$(grep -m1 "vendor_id" /proc/cpuinfo | cut -d: -f2 | sed 's/^[ \t]*//')
        
        # Get number of physical cores
        PHYSICAL_CORES=$(grep -c "core id" /proc/cpuinfo | uniq)
        
        # Get number of CPU threads (vCPUs)
        VCPUS=$(grep -c processor /proc/cpuinfo)
        
        # Get CPU family, model, and stepping
        FAMILY=$(grep -m1 "cpu family" /proc/cpuinfo | cut -d: -f2 | sed 's/^[ \t]*//')
        MODEL_NUM=$(grep -m1 "model" /proc/cpuinfo | grep -v "model name" | cut -d: -f2 | sed 's/^[ \t]*//')
        STEPPING=$(grep -m1 "stepping" /proc/cpuinfo | cut -d: -f2 | sed 's/^[ \t]*//')
        
        # Get cache size
        CACHE_SIZE=$(grep -m1 "cache size" /proc/cpuinfo | cut -d: -f2 | sed 's/^[ \t]*//')
        
        # Output as JSON for easy parsing
        echo "{\"model\": \"$MODEL\", \"vendor\": \"$VENDOR\", \"physical_cores\": $PHYSICAL_CORES, \"vcpus\": $VCPUS, \"family\": $FAMILY, \"model_num\": $MODEL_NUM, \"stepping\": $STEPPING, \"cache_size\": \"$CACHE_SIZE\"}"
      register: cpu_info
      changed_when: false

    - name: Set CPU facts
      set_fact:
        processor_model: "{{ cpu_info.stdout | from_json | json_query('model') }}"
        processor_vendor: "{{ cpu_info.stdout | from_json | json_query('vendor') }}"
        physical_cores: "{{ cpu_info.stdout | from_json | json_query('physical_cores') }}"
        vcpus: "{{ cpu_info.stdout | from_json | json_query('vcpus') }}"
        cpu_family: "{{ cpu_info.stdout | from_json | json_query('family') }}"
        cpu_model_num: "{{ cpu_info.stdout | from_json | json_query('model_num') }}"
        cpu_stepping: "{{ cpu_info.stdout | from_json | json_query('stepping') }}"
        cache_size: "{{ cpu_info.stdout | from_json | json_query('cache_size') }}"

    - name: Display detailed CPU information
      debug:
        msg:
          - "Processor Vendor: {{ processor_vendor }}"
          - "Processor Model: {{ processor_model }}"
          - "Physical Cores: {{ physical_cores }}"
          - "vCPUs/Threads: {{ vcpus }}"
          - "CPU Family: {{ cpu_family }}"
          - "CPU Model Number: {{ cpu_model_num }}"
          - "CPU Stepping: {{ cpu_stepping }}"
          - "Cache Size: {{ cache_size }}"
