---
- name: Get detailed CPU information from /proc/cpuinfo
  hosts: all  # Run on all hosts in inventory
  gather_facts: false
  tasks:
    - name: Read and parse /proc/cpuinfo
      shell: |
        # Get processor model
        MODEL=$(grep -m1 "model name" /proc/cpuinfo | cut -d: -f2 | sed 's/^[ \t]*//')
        
        # Get vendor/manufacturer
        VENDOR=$(grep -m1 "vendor_id" /proc/cpuinfo | cut -d: -f2 | sed 's/^[ \t]*//')
        
        # Get number of physical cores
        PHYSICAL_CORES=$(grep "core id" /proc/cpuinfo | sort -u | wc -l)
        
        # Get number of CPU threads (vCPUs)
        VCPUS=$(grep -c processor /proc/cpuinfo)
        
        # Get CPU family, model, and stepping
        FAMILY=$(grep -m1 "cpu family" /proc/cpuinfo | cut -d: -f2 | sed 's/^[ \t]*//')
        MODEL_NUM=$(grep -m1 "model" /proc/cpuinfo | grep -v "model name" | cut -d: -f2 | sed 's/^[ \t]*//')
        STEPPING=$(grep -m1 "stepping" /proc/cpuinfo | cut -d: -f2 | sed 's/^[ \t]*//')
        
        # Get cache size
        CACHE_SIZE=$(grep -m1 "cache size" /proc/cpuinfo | cut -d: -f2 | sed 's/^[ \t]*//')
        
        # Output as JSON for easy parsing
        echo "{\"model\": \"$MODEL\", \"vendor\": \"$VENDOR\", \"physical_cores\": $PHYSICAL_CORES, \"vcpus\": $VCPUS, \"family\": $FAMILY, \"model_num\": $MODEL_NUM, \"stepping\": $STEPPING, \"cache_size\": \"$CACHE_SIZE\"}"
      register: cpu_info
      changed_when: false

    - name: Display detailed CPU information
      debug:
        msg:
          - "Host: {{ inventory_hostname }}"
          - "Processor Vendor: {{ (cpu_info.stdout | from_json).vendor }}"
          - "Processor Model: {{ (cpu_info.stdout | from_json).model }}"
          - "Physical Cores: {{ (cpu_info.stdout | from_json).physical_cores }}"
          - "vCPUs/Threads: {{ (cpu_info.stdout | from_json).vcpus }}"
          - "CPU Family: {{ (cpu_info.stdout | from_json).family }}"
          - "CPU Model Number: {{ (cpu_info.stdout | from_json).model_num }}"
          - "CPU Stepping: {{ (cpu_info.stdout | from_json).stepping }}"
          - "Cache Size: {{ (cpu_info.stdout | from_json).cache_size }}"
