---
- name: Simple LMDE 6 security updates
  hosts: all
  become: true
  
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Upgrade security packages only
      apt:
        upgrade: safe
        autoremove: yes
        autoclean: yes
