---
- name: Update and upgrade system packages on all machines
  hosts: all
  become: true
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      register: apt_update
      changed_when: apt_update.cache_updated

    - name: Full system upgrade (safe + handles dependency changes)
      ansible.builtin.apt:
        upgrade: full
        autoclean: yes
      register: apt_upgrade
      changed_when: apt_upgrade.changed

    - name: Remove unused packages
      ansible.builtin.apt:
        autoremove: yes
      register: apt_autoremove
      changed_when: apt_autoremove.changed

    - name: Display update summary
      ansible.builtin.debug:
        msg: >-
          {{ inventory_hostname }}:
          cache_updated={{ apt_update.cache_updated }},
          packages_upgraded={{ apt_upgrade.changed }},
          autoremoved={{ apt_autoremove.changed }}
